[build-system]
requires = [
    "pip",
    "setuptools",
    "wheel",
    "pybind11>=2.8.0",
    "libcasm-global>=2.0.6",
    "libcasm-xtal>=2.0.0",
    "libcasm-clexulator>=2.0.0",
]
build-backend = "setuptools.build_meta"
